name: Deploy Jekyll Site to GitHub Pages

on:
  push:
    branches: ["main"]  # Trigger on push to main branch
  workflow_dispatch:  # Allow manual trigger

permissions:
  contents: read
  pages: write
  id-token: write

concurrency: 
  group: "pages-deployment"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # Checkout your repository content
      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5  # Configures GitHub Pages environment
      - name: Build Jekyll Site
        uses: actions/jekyll-build-pages@v1  # Builds your Jekyll site
        with:
          source: ./
          destination: ./_site  # Output directory for the Jekyll build
      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3  # Uploads the build to be used by the deploy job

  deploy:
    needs: build  # Ensures deploy job runs after build job
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4  # Deploys the site to GitHub Pages
